try:
    print(z)
except Exception as e:
    print(e)
